export const PROSENSE_LOADING ="PROSENSE_LOADING";
export const PROSENSE_SUCCESS ="PROSENSE_SUCCESS";
export const PROSENSE_ERROR ="PROSENSE_ERROR";
export const PROSENSE_RELOADING ="PROSENSE_RELOADING";

export const LOADING ="LOADING";
export const ERROR ="ERROR";
export const SUCCESS ="SUCCESS";
export const RELOADING ="RELOADING";
export const NONE ="NONE";
export const GET_SAMPLE="GET_SAMPLE";
export const SAMPLE_ERROR="SAMPLE_ERROR";

export const SET_CLASS_LOADING = "SET_CLASS_LOADING";
export const SET_CLASS_SUCCESS = "SET_CLASS_SUCCESS";
export const SET_CLASS_ERROR = "SET_CLASS_ERROR";

export const TOGGLE_ADD_OBJECT_MODEL_LOADING = "TOGGLE_ADD_OBJECT_MODEL_LOADING";
export const TOGGLE_ADD_OBJECT_MODEL_SUCCESS = "TOGGLE_ADD_OBJECT_MODEL_SUCCESS";
export const TOGGLE_ADD_OBJECT_MODEL_ERROR = "TOGGLE_ADD_OBJECT_MODEL_ERROR";