// PROPSENSE REDUCER
export const PROSENSE_LOADING ="PROSENSE_LOADING";
export const PROSENSE_SUCCESS ="PROSENSE_SUCCESS";
export const PROSENSE_ERROR ="PROSENSE_ERROR";
export const PROSENSE_RELOADING ="PROSENSE_RELOADING";

export const LOADING ="LOADING";
export const ERROR ="ERROR";
export const SUCCESS ="SUCCESS";
export const RELOADING ="RELOADING";
export const NONE ="NONE";
export const GET_SAMPLE="GET_SAMPLE";
export const SAMPLE_ERROR="SAMPLE_ERROR";


// CLASS REDUCER
export const SET_CLASS_LOADING = "SET_CLASS_LOADING";
export const SET_CLASS_SUCCESS = "SET_CLASS_SUCCESS";
export const SET_CLASS_ERROR = "SET_CLASS_ERROR";

export const TOGGLE_ADD_OBJECT_MODEL_LOADING = "TOGGLE_ADD_OBJECT_MODEL_LOADING";
export const TOGGLE_ADD_OBJECT_MODEL_SUCCESS = "TOGGLE_ADD_OBJECT_MODEL_SUCCESS";
export const TOGGLE_ADD_OBJECT_MODEL_ERROR = "TOGGLE_ADD_OBJECT_MODEL_ERROR";

export const GET_ALL_CLASS_LOADING = "GET_ALL_CLASS_LOADING";
export const GET_ALL_CLASS_SUCCESS = "GET_ALL_CLASS_SUCCESS";
export const GET_ALL_CLASS_ERROR = "GET_ALL_CLASS_ERROR";

export const BREADCRUMB_LOADING = "BREADCRUMB_LOADING";
export const BREADCRUMB_SUCCESS = "BREADCRUMB_SUCCESS";
export const BREADCRUMB_ERROR = "BREADCRUMB_ERROR";

export const TOGGLE_ADD_CLASS_OBJECT_MODEL_LOADING = "TOGGLE_ADD_CLASS_OBJECT_MODEL_LOADING";
export const TOGGLE_ADD_CLASS_OBJECT_MODEL_SUCCESS = "TOGGLE_ADD_CLASS_OBJECT_MODEL_SUCCESS";
export const TOGGLE_ADD_CLASS_OBJECT_MODEL_ERROR = "TOGGLE_ADD_CLASS_OBJECT_MODEL_ERROR";

export const OBJ_SELECT_DEFAULT_CLASS_LOADING = "OBJ_SELECT_DEFAULT_CLASS_LOADING";
export const OBJ_SELECT_DEFAULT_CLASS_SUCCESS = "OBJ_SELECT_DEFAULT_CLASS_SUCCESS";
export const OBJ_SELECT_DEFAULT_CLASS_ERROR = "OBJ_SELECT_DEFAULT_CLASS_ERROR";

export const OBJ_SELECT_DEFAULT_SUB_CLASS_LOADING = "OBJ_SELECT_DEFAULT_SUB_CLASS_LOADING";
export const OBJ_SELECT_DEFAULT_SUB_CLASS_SUCCESS = "OBJ_SELECT_DEFAULT_SUB_CLASS_SUCCESS";
export const OBJ_SELECT_DEFAULT_SUB_CLASS_ERROR = "OBJ_SELECT_DEFAULT_SUB_CLASS_ERROR";

export const SUCCESS_MESSAGE_LOADING = "SUCCESS_MESSAGE_LOADING";
export const SUCCESS_MESSAGE_SUCCESS = "SUCCESS_MESSAGE_SUCCESS";
export const SUCCESS_MESSAGE_ERROR = "SUCCESS_MESSAGE_ERROR";

export const DATA_FOR_EOPSWATCH_LOADING = "DATA_FOR_EOPSWATCH_LOADING";
export const DATA_FOR_EOPSWATCH_SUCCESS = "DATA_FOR_EOPSWATCH_SUCCESS";
export const DATA_FOR_EOPSWATCH_ERROR = "DATA_FOR_EOPSWATCH_ERROR";


export const EDIT_CLASS_MODEL_LOADING = "EDIT_CLASS_MODEL_LOADING";
export const EDIT_CLASS_MODEL_SUCCESS = "EDIT_CLASS_MODEL_SUCCESS";
export const EDIT_CLASS_MODEL_ERROR = "EDIT_CLASS_MODEL_ERROR";

export const EDIT_SUB_CLASS_MODEL_LOADING = "EDIT_SUB_CLASS_MODEL_LOADING";
export const EDIT_SUB_CLASS_MODEL_SUCCESS = "EDIT_SUB_CLASS_MODEL_SUCCESS";
export const EDIT_SUB_CLASS_MODEL_ERROR = "EDIT_SUB_CLASS_MODEL_ERROR";

export const EDIT_OBJECT_MODEL_LOADING = "EDIT_OBJECT_MODEL_LOADING";
export const EDIT_OBJECT_MODEL_SUCCESS = "EDIT_OBJECT_MODEL_SUCCESS";
export const EDIT_OBJECT_MODEL_ERROR = "EDIT_OBJECT_MODEL_ERROR";

export const EDIT_SUB_OBJECT_MODEL_LOADING = "EDIT_SUB_OBJECT_MODEL_LOADING";
export const EDIT_SUB_OBJECT_MODEL_SUCCESS = "EDIT_SUB_OBJECT_MODEL_SUCCESS";
export const EDIT_SUB_OBJECT_MODEL_ERROR = "EDIT_SUB_OBJECT_MODEL_ERROR";

export const NEW_CLASS_MODEL_LOADING = "NEW_CLASS_MODEL_LOADING";
export const NEW_CLASS_MODEL_SUCCESS = "NEW_CLASS_MODEL_SUCCESS";
export const NEW_CLASS_MODEL_ERROR = "NEW_CLASS_MODEL_ERROR";

export const SET_DATA_FOR_SUB_OBJECT_LOADING = "SET_DATA_FOR_SUB_OBJECT_LOADING";
export const SET_DATA_FOR_SUB_OBJECT_SUCCESS = "SET_DATA_FOR_SUB_OBJECT_SUCCESS";
export const SET_DATA_FOR_SUB_OBJECT_ERROR = "SET_DATA_FOR_SUB_OBJECT_ERROR";

export const SUCCESS_MESSAGE_WITH_TYPE_LOADING = "SUCCESS_MESSAGE_WITH_TYPE_LOADING";
export const SUCCESS_MESSAGE_WITH_TYPE_SUCCESS = "SUCCESS_MESSAGE_WITH_TYPE_SUCCESS";
export const SUCCESS_MESSAGE_WITH_TYPE_ERROR = "SUCCESS_MESSAGE_WITH_TYPE_ERROR";

export const SELECTED_CLASS_LOADING = "SELECTED_CLASS_LOADING";
export const SELECTED_CLASS_SUCCESS = "SELECTED_CLASS_SUCCESS";
export const SELECTED_CLASS_ERROR = "SELECTED_CLASS_ERROR";

export const SELECTED_SUB_CLASS_LOADING = "SELECTED_SUB_CLASS_LOADING";
export const SELECTED_SUB_CLASS_SUCCESS = "SELECTED_SUB_CLASS_SUCCESS";
export const SELECTED_SUB_CLASS_ERROR = "SELECTED_SUB_CLASS_ERROR";

export const SELECTED_OBJECT_LOADING = "SELECTED_OBJECT_LOADING";
export const SELECTED_OBJECT_SUCCESS = "SELECTED_OBJECT_SUCCESS";
export const SELECTED_OBJECT_ERROR = "SELECTED_OBJECT_ERROR";

export const SELECTED_SUB_OBJECT_LOADING = "SELECTED_SUB_OBJECT_LOADING";
export const SELECTED_SUB_OBJECT_SUCCESS = "SELECTED_SUB_OBJECT_SUCCESS";
export const SELECTED_SUB_OBJECT_ERROR = "SELECTED_SUB_OBJECT_ERROR";


// API REDUCER
export const GET_CLASS_API_LOADING = "GET_CLASS_API_LOADING";
export const GET_CLASS_API_SUCCESS = "GET_CLASS_API_SUCCESS";
export const GET_CLASS_API_ERROR = "GET_CLASS_API_ERROR";

export const GET_DATA_TYPE_LOADING = "GET_DATA_TYPE_LOADING";
export const GET_DATA_TYPE_SUCCESS = "GET_DATA_TYPE_SUCCESS";
export const GET_DATA_TYPE_ERROR = "GET_DATA_TYPE_ERROR";

export const GET_SUB_CLASS_API_LOADING = "GET_SUB_CLASS_API_LOADING";
export const GET_SUB_CLASS_API_SUCCESS = "GET_SUB_CLASS_API_SUCCESS";
export const GET_SUB_CLASS_API_ERROR = "GET_SUB_CLASS_API_ERROR";

export const GET_OBJECT_API_LOADING = "GET_OBJECT_API_LOADING";
export const GET_OBJECT_API_SUCCESS = "GET_OBJECT_API_SUCCESS";
export const GET_OBJECT_API_ERROR = "GET_OBJECT_API_ERROR";

export const SET_SELECTED_CLASS_SUCCESS = "SET_SELECTED_CLASS_SUCCESS";
export const SET_SELECTED_CLASS_ERROR = "SET_SELECTED_CLASS_ERROR";

export const GET_OBJECTS_SUCCESS = "GET_OBJECTS_SUCCESS";
export const GET_OBJECTS_ERROR = "GET_OBJECTS_ERROR";


// AI MODAL DETECTION REDUCER
export const DATA_FOR_MODEL_LOADING = "DATA_FOR_MODEL_LOADING";
export const DATA_FOR_MODEL_SUCCESS = "DATA_FOR_MODEL_SUCCESS";
export const DATA_FOR_MODEL_ERROR = "DATA_FOR_MODEL_ERROR";

export const GET_CLASS_FROM_ID_LOADING = "GET_CLASS_FROM_ID_LOADING";
export const GET_CLASS_FROM_ID_SUCCESS = "GET_CLASS_FROM_ID_SUCCESS";
export const GET_CLASS_FROM_ID_ERROR = "GET_CLASS_FROM_ID_ERROR";

export const GET_SUB_CLASS_FROM_ID_LOADING = "GET_SUB_CLASS_FROM_ID_LOADING";
export const GET_SUB_CLASS_FROM_ID_SUCCESS = "GET_SUB_CLASS_FROM_ID_SUCCESS";
export const GET_SUB_CLASS_FROM_ID_ERROR = "GET_SUB_CLASS_FROM_ID_ERROR";

export const GET_OBJECT_FROM_ID_LOADING = "GET_OBJECT_FROM_ID_LOADING";
export const GET_OBJECT_FROM_ID_SUCCESS = "GET_OBJECT_FROM_ID_SUCCESS";
export const GET_OBJECT_FROM_ID_ERROR = "GET_OBJECT_FROM_ID_ERROR";

export const GET_SUB_OBJECT_FROM_ID_LOADING = "GET_SUB_OBJECT_FROM_ID_LOADING";
export const GET_SUB_OBJECT_FROM_ID_SUCCESS = "GET_SUB_OBJECT_FROM_ID_SUCCESS";
export const GET_SUB_OBJECT_FROM_ID_ERROR = "GET_SUB_OBJECT_FROM_ID_ERROR";

export const GET_MODEL_IMAGES_LOADING = "GET_MODEL_IMAGES_LOADING";
export const GET_MODEL_IMAGES_SUCCESS = "GET_MODEL_IMAGES_SUCCESS";
export const GET_MODEL_IMAGES_ERROR = "GET_MODEL_IMAGES_ERROR";

export const GET_ALL_MODEL_SUCCESS = "GET_ALL_MODEL_SUCCESS";
export const GET_ALL_MODEL_ERROR = "GET_ALL_MODEL_ERROR";
export const GET_ALL_MODEL_LOADING = "GET_ALL_MODEL_LOADING";

export const GET_CLASSNAME_FROM_CLASS_ID_SUCCESS = "GET_CLASSNAME_FROM_CLASS_ID_SUCCESS";
export const GET_CLASSNAME_FROM_CLASS_ID_ERROR = "GET_CLASSNAME_FROM_CLASS_ID_ERROR";

export const GET_OBJECT_FROM_OBJECT_ID_SUCCESS = "GET_OBJECT_FROM_OBJECT_ID_SUCCESS";
export const GET_OBJECT_FROM_OBJECT_ID_ERROR = "GET_OBJECT_FROM_OBJECT_ID_ERROR";

export const GET_SUB_CLASSNAME_FROM_SUB_CLASS_ID_SUCCESS = "GET_SUB_CLASSNAME_FROM_SUB_CLASS_ID_SUCCESS";
export const GET_SUB_CLASSNAME_FROM_SUB_CLASS_ID_ERROR = "GET_SUB_CLASSNAME_FROM_SUB_CLASS_ID_ERROR";

export const GET_SUB_OBJECT_FROM_SUB_OBJECT_ID_SUCCESS = "GET_SUB_OBJECT_FROM_SUB_OBJECT_ID_SUCCESS";
export const GET_SUB_OBJECT_FROM_SUB_OBJECT_ID_ERROR = "GET_SUB_OBJECT_FROM_SUB_OBJECT_ID_ERROR";

export const SAVE_RESPONSE_FROM_TEST_SUCCESS = "SAVE_RESPONSE_FROM_TEST_SUCCESS";
export const SAVE_RESPONSE_FROM_TEST_ERROR = "SAVE_RESPONSE_FROM_TEST_ERROR";



// USERS
export const GET_USERS_BY_ID_SUCCESS = "GET_USERS_BY_ID_SUCCESS";
export const GET_USERS_BY_ID_ERROR = "GET_USERS_BY_ID_ERROR";

export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_ERROR = "GET_ALL_USERS_ERROR";


// Authentication 
export const SAVE_USER_DATA_FIRST_STEP_SUCCESS = "SAVE_USER_DATA_FIRST_STEP_SUCCESS";
export const SAVE_USER_DATA_FIRST_STEP_ERROR = "SAVE_USER_DATA_FIRST_STEP_ERROR";

export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_ERROR = "VERIFY_OTP_ERROR";