export const PROSENSE_LOADING ="PROSENSE_LOADING";
export const PROSENSE_SUCCESS ="PROSENSE_SUCCESS";
export const PROSENSE_ERROR ="PROSENSE_ERROR";
export const PROSENSE_RELOADING ="PROSENSE_RELOADING";

export const LOADING ="LOADING";
export const ERROR ="ERROR";
export const SUCCESS ="SUCCESS";
export const RELOADING ="RELOADING";
export const NONE ="NONE";
export const GET_SAMPLE="GET_SAMPLE";
export const SAMPLE_ERROR="SAMPLE_ERROR";

export const SET_CLASS_LOADING = "SET_CLASS_LOADING";
export const SET_CLASS_SUCCESS = "SET_CLASS_SUCCESS";
export const SET_CLASS_ERROR = "SET_CLASS_ERROR";

export const TOGGLE_ADD_OBJECT_MODEL_LOADING = "TOGGLE_ADD_OBJECT_MODEL_LOADING";
export const TOGGLE_ADD_OBJECT_MODEL_SUCCESS = "TOGGLE_ADD_OBJECT_MODEL_SUCCESS";
export const TOGGLE_ADD_OBJECT_MODEL_ERROR = "TOGGLE_ADD_OBJECT_MODEL_ERROR";

export const GET_ALL_CLASS_LOADING = "GET_ALL_CLASS_LOADING";
export const GET_ALL_CLASS_SUCCESS = "GET_ALL_CLASS_SUCCESS";
export const GET_ALL_CLASS_ERROR = "GET_ALL_CLASS_ERROR";

export const BREADCRUMB_LOADING = "BREADCRUMB_LOADING";
export const BREADCRUMB_SUCCESS = "BREADCRUMB_SUCCESS";
export const BREADCRUMB_ERROR = "BREADCRUMB_ERROR";

export const TOGGLE_ADD_CLASS_OBJECT_MODEL_LOADING = "TOGGLE_ADD_CLASS_OBJECT_MODEL_LOADING";
export const TOGGLE_ADD_CLASS_OBJECT_MODEL_SUCCESS = "TOGGLE_ADD_CLASS_OBJECT_MODEL_SUCCESS";
export const TOGGLE_ADD_CLASS_OBJECT_MODEL_ERROR = "TOGGLE_ADD_CLASS_OBJECT_MODEL_ERROR";

export const OBJ_SELECT_DEFAULT_CLASS_LOADING = "OBJ_SELECT_DEFAULT_CLASS_LOADING";
export const OBJ_SELECT_DEFAULT_CLASS_SUCCESS = "OBJ_SELECT_DEFAULT_CLASS_SUCCESS";
export const OBJ_SELECT_DEFAULT_CLASS_ERROR = "OBJ_SELECT_DEFAULT_CLASS_ERROR";

export const OBJ_SELECT_DEFAULT_SUB_CLASS_LOADING = "OBJ_SELECT_DEFAULT_SUB_CLASS_LOADING";
export const OBJ_SELECT_DEFAULT_SUB_CLASS_SUCCESS = "OBJ_SELECT_DEFAULT_SUB_CLASS_SUCCESS";
export const OBJ_SELECT_DEFAULT_SUB_CLASS_ERROR = "OBJ_SELECT_DEFAULT_SUB_CLASS_ERROR";

export const SUCCESS_MESSAGE_LOADING = "SUCCESS_MESSAGE_LOADING";
export const SUCCESS_MESSAGE_SUCCESS = "SUCCESS_MESSAGE_SUCCESS";
export const SUCCESS_MESSAGE_ERROR = "SUCCESS_MESSAGE_ERROR";

export const DATA_FOR_EOPSWATCH_LOADING = "DATA_FOR_EOPSWATCH_LOADING";
export const DATA_FOR_EOPSWATCH_SUCCESS = "DATA_FOR_EOPSWATCH_SUCCESS";
export const DATA_FOR_EOPSWATCH_ERROR = "DATA_FOR_EOPSWATCH_ERROR";


export const EDIT_CLASS_MODEL_LOADING = "EDIT_CLASS_MODEL_LOADING";
export const EDIT_CLASS_MODEL_SUCCESS = "EDIT_CLASS_MODEL_SUCCESS";
export const EDIT_CLASS_MODEL_ERROR = "EDIT_CLASS_MODEL_ERROR";

export const EDIT_SUB_CLASS_MODEL_LOADING = "EDIT_SUB_CLASS_MODEL_LOADING";
export const EDIT_SUB_CLASS_MODEL_SUCCESS = "EDIT_SUB_CLASS_MODEL_SUCCESS";
export const EDIT_SUB_CLASS_MODEL_ERROR = "EDIT_SUB_CLASS_MODEL_ERROR";

export const EDIT_OBJECT_MODEL_LOADING = "EDIT_OBJECT_MODEL_LOADING";
export const EDIT_OBJECT_MODEL_SUCCESS = "EDIT_OBJECT_MODEL_SUCCESS";
export const EDIT_OBJECT_MODEL_ERROR = "EDIT_OBJECT_MODEL_ERROR";

export const EDIT_SUB_OBJECT_MODEL_LOADING = "EDIT_SUB_OBJECT_MODEL_LOADING";
export const EDIT_SUB_OBJECT_MODEL_SUCCESS = "EDIT_SUB_OBJECT_MODEL_SUCCESS";
export const EDIT_SUB_OBJECT_MODEL_ERROR = "EDIT_SUB_OBJECT_MODEL_ERROR";

export const DATA_FOR_EOPSTRACE_LOADING = "DATA_FOR_EOPSTRACE_LOADING";
export const DATA_FOR_EOPSTRACE_SUCCESS = "DATA_FOR_EOPSTRACE_SUCCESS";
export const DATA_FOR_EOPSTRACE_ERROR = "DATA_FOR_EOPSTRACE_ERROR";

export const DATA_FROM_RESULT_PAGE_LOADING = "DATA_FROM_RESULT_PAGE_LOADING";
export const DATA_FROM_RESULT_PAGE_SUCCESS = "DATA_FROM_RESULT_PAGE_SUCCESS";
export const DATA_FROM_RESULT_PAGE_ERROR = "DATA_FROM_RESULT_PAGE_ERROR";

export const DATA_FOR_ALERTS_LOADING = "DATA_FOR_ALERTS_LOADING";
export const DATA_FOR_ALERTS_SUCCESS = "DATA_FOR_ALERTS_SUCCESS";
export const DATA_FOR_ALERTS_ERROR = "DATA_FOR_ALERTS_ERROR";


export const SAVE_DATA_FLOW_OBJECT_MANAGEMENT_SUCCESS = "SAVE_DATA_FLOW_OBJECT_MANAGEMENT_SUCCESS";
export const SAVE_DATA_FLOW_OBJECT_MANAGEMENT_ERROR = "SAVE_DATA_FLOW_OBJECT_MANAGEMENT_ERROR"